from __future__ import annotations
import sys
import os
from pathlib import Path
import time
import base64
import tempfile
from typing import Optional

SRC_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SRC_DIR))

import streamlit as st
import fitz
from rag_pipeline import RAGPipeline, ingest_pdf, load_pdf_cache, RAGResult
from confidence import confidence_label, confidence_color

st.set_page_config(page_title="Elite RAG Premium", page_icon="✨", layout="wide", initial_sidebar_state="expanded")

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap');
:root { --bg: #131314; --surface: #1e1f20; --surface2: #2a2b2e; --border: #33363d; --accent: #a8c7fa; --text: #e3e3e3; --muted: #8e918f; }
html, body, [data-testid="stAppViewContainer"] { background: var(--bg) !important; color: var(--text); font-family: 'Inter', sans-serif; }
[data-testid="stHeader"] { background: transparent !important; } #MainMenu, footer { visibility: hidden; }
[data-testid="stSidebar"] { background: var(--surface) !important; border-right: 1px solid var(--border); }
.pdf-container { background: var(--surface); padding: 1rem; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.2); text-align: center; height: 70vh; overflow-y: auto; }
.badge-row { display: flex; flex-wrap: wrap; gap: 8px; margin: 8px 0; align-items: center; }
.pill { background: var(--surface); border: 1px solid var(--border); padding: 4px 10px; border-radius: 12px; font-size: 0.75rem; display: inline-flex; align-items: center; gap: 4px; }
div[data-testid="stExpander"] { background: transparent !important; border: 1px solid var(--border) !important; border-radius: 12px !important; }
.dot-typing { display: flex; gap: 4px; padding: 8px 0; }
.dot-typing .dot { width: 6px; height: 6px; background-color: var(--accent); border-radius: 50%; animation: typing 1.4s infinite ease-in-out both; }
.dot-typing .dot:nth-child(1) { animation-delay: -0.32s; } .dot-typing .dot:nth-child(2) { animation-delay: -0.16s; }
@keyframes typing { 0%, 80%, 100% { transform: scale(0); opacity: 0.3; } 40% { transform: scale(1); opacity: 1; } }
[data-testid="stTextInput"] input { background: var(--surface) !important; border-radius: 20px !important; border: 1px solid var(--border) !important; padding: 14px 24px !important; font-size: 1.05rem !important; color: white !important; box-shadow: 0 4px 15px rgba(0,0,0,0.2) !important; }
[data-testid="stTextInput"] input:focus { border-color: var(--accent) !important; }
button[kind="secondary"] { background: var(--surface2) !important; border: 1px solid var(--border) !important; border-radius: 12px !important; color: var(--accent) !important; padding: 2px 10px !important; min-height: 0 !important; height: 32px !important; width: 100% !important; }
</style>
""", unsafe_allow_html=True)

CACHE_DIR = Path(tempfile.gettempdir()) / "elite_rag_cache"
CACHE_DIR.mkdir(exist_ok=True)

DEFAULT_CFG = {
    "candidate_k": 20, "final_k": 5, "max_tokens": 512, "context_window": 1, 
    "abs_threshold": 0.25, "use_hyde": False
}

if "pipelines" not in st.session_state:
    st.session_state.update({
        "pipelines": {}, "active_pdf": None, "pdf_bytes": {}, "chat_history": [], 
        "view_page": 1, "search_mode": "hybrid", "cfg": DEFAULT_CFG.copy(), 
        "pending_query": None, "user_input": ""
    })
ss = st.session_state

def render_pdf_page(pdf_bytes: bytes, page_num: int, highlight_text: str = "") -> str:
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    page_num = max(1, min(page_num, len(doc)))
    page = doc[page_num - 1]
    if highlight_text:
        for phrase in highlight_text.split("."):
            if len(phrase.strip()) > 20:
                for rect in page.search_for(phrase.strip()[:60]): 
                    page.add_highlight_annot(rect)
    img_bytes = page.get_pixmap(matrix=fitz.Matrix(2.0, 2.0), alpha=False).tobytes("png")
    doc.close()
    return base64.b64encode(img_bytes).decode()

def build_badges(result: RAGResult) -> str:
    c_color = confidence_color(result.confidence_score)
    c_pct = int(result.confidence_score * 100)
    return f'<div class="badge-row"><span class="pill" style="color:{c_color}; border-color:{c_color}40; background:{c_color}10;">✨ {confidence_label(result.confidence_score)} ({c_pct}%)</span></div>'

def submit_query():
    if ss.user_input.strip(): 
        ss.pending_query = ss.user_input.strip()
        ss.user_input = ""

def generate_markdown_report(history: list, pdf_name: str) -> str:
    md = f"# Research Report: {pdf_name}\n*Generated by Elite RAG*\n\n---\n\n"
    for item in history:
        md += f"### Q: {item['q']}\n\n**A:** {item['result'].answer}\n\n"
        if item['result'].retrieved:
            pages = sorted(list(set([r.page for r in item['result'].retrieved])))
            md += f"*Sources: Pages {pages}*\n\n---\n"
    return md

with st.sidebar:
    st.markdown("### 📚 Documents")
    if ss.pipelines:
        stems = list(ss.pipelines.keys())
        chosen = st.radio("Active Document", [ss.pipelines[s].pdf_name for s in stems], index=stems.index(ss.active_pdf) if ss.active_pdf in stems else 0, label_visibility="collapsed")
        
        if chosen != ss.pipelines[ss.active_pdf].pdf_name:
            ss.active_pdf = stems[[ss.pipelines[s].pdf_name for s in stems].index(chosen)]
            st.rerun()
            
        with st.expander("+ Add Document", expanded=False):
            new_doc = st.file_uploader("Upload", type=["pdf"], label_visibility="collapsed", key="add_doc")
            if new_doc:
                with st.spinner("Processing..."):
                    stem = Path(new_doc.name).stem
                    if stem not in ss.pipelines:
                        p_bytes = new_doc.read()
                        ss.pdf_bytes[stem] = p_bytes
                        cached = load_pdf_cache(p_bytes, CACHE_DIR)
                        if cached: 
                            chunks, vs, summary = cached[0], cached[1], "Document loaded from cache."
                        else: 
                            chunks, vs, summary = ingest_pdf(p_bytes, new_doc.name, CACHE_DIR, ss.cfg)
                        ss.pipelines[stem] = RAGPipeline(chunks, vs, new_doc.name, ss.cfg, summary)
                        ss.active_pdf = stem
                    st.rerun()

    st.divider()
    st.markdown("### ⚡ AI Engine")
    
    ss.search_mode = st.selectbox("Search Mode", ["hybrid", "vector", "bm25"], index=["hybrid", "vector", "bm25"].index(ss.search_mode))
    ss.cfg["use_hyde"] = st.toggle("Use HyDE (Query Expansion)", value=ss.cfg["use_hyde"], help="Increases accuracy for short queries by generating a hypothetical answer first.")

    with st.expander("Advanced Parameters", expanded=False):
        ss.cfg["abs_threshold"]  = st.slider("Confidence filter", 0.0, 0.8, ss.cfg["abs_threshold"], 0.01)
        ss.cfg["candidate_k"]    = st.slider("Candidate K", 5, 50, ss.cfg["candidate_k"])
        ss.cfg["final_k"]        = st.slider("Final K", 1, 10, ss.cfg["final_k"])
        ss.cfg["max_tokens"]     = st.slider("Max tokens", 128, 1024, ss.cfg["max_tokens"], 64)
    
    if ss.active_pdf:
        st.divider()
        current_hist = [msg for msg in ss.chat_history if msg["pdf"] == ss.active_pdf]
        if current_hist:
            st.download_button("📥 Download Report (MD)", generate_markdown_report(current_hist, ss.pipelines[ss.active_pdf].pdf_name), file_name=f"{ss.active_pdf}_report.md", mime="text/markdown", use_container_width=True)
        if st.button("🗑 Clear Chat", use_container_width=True):
            ss.chat_history = [msg for msg in ss.chat_history if msg["pdf"] != ss.active_pdf]
            st.rerun()

if not ss.pipelines:
    st.markdown("<h1 style='text-align: center; margin-top: 25vh; font-weight: 400;'>What are we researching today?</h1>", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        uploaded = st.file_uploader(" ", type=["pdf"], label_visibility="collapsed")
        if uploaded:
            with st.spinner("Initializing Workspace..."):
                stem = Path(uploaded.name).stem
                p_bytes = uploaded.read()
                ss.pdf_bytes[stem] = p_bytes
                cached = load_pdf_cache(p_bytes, CACHE_DIR)
                if cached: 
                    chunks, vs, summary = cached[0], cached[1], "Document loaded from cache."
                else: 
                    chunks, vs, summary = ingest_pdf(p_bytes, uploaded.name, CACHE_DIR, ss.cfg)
                ss.pipelines[stem] = RAGPipeline(chunks, vs, uploaded.name, ss.cfg, summary)
                ss.active_pdf = stem
            st.rerun()
    st.stop()

left_col, right_col = st.columns([1, 1], gap="large")
pipeline: RAGPipeline = ss.pipelines[ss.active_pdf]
pipeline.cfg = ss.cfg 
current_history = [msg for msg in ss.chat_history if msg["pdf"] == ss.active_pdf]

with left_col:
    pdf_bytes = ss.pdf_bytes.get(ss.active_pdf, b"")
    if pdf_bytes:
        last_result: Optional[RAGResult] = current_history[-1]["result"] if current_history else None
        c1, c2, c3, c4 = st.columns([1, 2, 2, 1])
        with c2: 
            if st.button("◀", use_container_width=True): 
                ss.view_page = max(1, ss.view_page - 1)
        with c3:
            total_pgs = fitz.open(stream=pdf_bytes, filetype="pdf").page_count
            ss.view_page = st.number_input("Pg", min_value=1, max_value=total_pgs, value=ss.view_page, label_visibility="collapsed")
        with c4:
            if st.button("▶", use_container_width=True): 
                ss.view_page = min(total_pgs, ss.view_page + 1)

        highlight = ""
        if last_result and last_result.retrieved and last_result.retrieved[0].page == ss.view_page:
            highlight = last_result.retrieved[0].text[:200]
            
        st.markdown(
            f'<div class="pdf-container"><img src="data:image/png;base64,{render_pdf_page(pdf_bytes, ss.view_page, highlight)}" style="width: 100%; border-radius: 4px;"/></div>', 
            unsafe_allow_html=True
        )

with right_col:
    st.text_input("Search", key="user_input", on_change=submit_query, placeholder="Ask about the document and press Enter...", label_visibility="collapsed")
    
    with st.container(height=650, border=False):
        
        if not current_history and not ss.pending_query and pipeline.summary:
            st.markdown(f"""
            <div style="background:var(--surface); padding:1.2rem; border-radius:12px; border:1px solid var(--border); margin-bottom:1rem;">
                <strong style="color:var(--accent); font-size:1.1rem;">✨ Document Summary</strong><br><br>
                <div style="color:var(--text); line-height:1.6;">{pipeline.summary}</div>
            </div>
            """, unsafe_allow_html=True)

        for msg_idx, item in enumerate(current_history):
            with st.chat_message("user"): 
                st.write(item["q"])
                
            with st.chat_message("assistant"):
                if item.get("is_new", False):
                    def stream_words():
                        for word in item["result"].answer.split(" "):
                            yield word + " "
                            time.sleep(0.02)
                    st.write_stream(stream_words)
                    for glob_item in ss.chat_history:
                        if glob_item is item: 
                            glob_item["is_new"] = False
                else: 
                    st.write(item["result"].answer)
                    
                st.markdown(build_badges(item["result"]), unsafe_allow_html=True)
                
                if item["result"].retrieved:
                    pages = sorted(list(set([r.page for r in item["result"].retrieved])))
                    if pages:
                        st.markdown("<div style='font-size:0.75rem; color:var(--muted); margin: 4px 0;'>Reference Pages:</div>", unsafe_allow_html=True)
                        cols = st.columns(4) 
                        for j, pg in enumerate(pages):
                            with cols[j % 4]:
                                if st.button(f"📄 p.{pg}", key=f"hj_{msg_idx}_{pg}"): 
                                    ss.view_page = pg
                                    st.rerun()

                    with st.expander("View Source Text"):
                        for chunk in item["result"].retrieved:
                            section_str = chunk.section if chunk.section else "General"
                            st.markdown(
                                f'<div style="font-size:0.8rem; padding:8px; border-bottom:1px solid var(--border);">'
                                f'<strong style="color:var(--accent)">p.{chunk.page} | § {section_str[:40]}...</strong><br/>'
                                f'<span style="color:var(--muted)">{chunk.text[:150]}...</span></div>', 
                                unsafe_allow_html=True
                            )
                            
        if ss.pending_query:
            with st.chat_message("user"): 
                st.write(ss.pending_query)
                
            with st.chat_message("assistant"): 
                st.markdown(
                    '<div class="dot-typing"><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>', 
                    unsafe_allow_html=True
                )
                
            result = pipeline.query(ss.pending_query, search_mode=ss.search_mode)
            ss.chat_history.append({"pdf": ss.active_pdf, "q": ss.pending_query, "result": result, "is_new": True})
            
            if result.retrieved: 
                ss.view_page = result.retrieved[0].page
                
            ss.pending_query = None
            st.rerun()